### ISSUE TITLE
Errors while using script

### ISSUE THREAD

**Issue by blackerking** [jpkorva/dudle-docker#3]
Everytime I use the scripts: scripts/maintenance/dudle-maint.sh backup / start / stop...
I get an error:  6: [: 424466157e1d: unexpected operator 424466157e1d
The Number is the name of the docker container.

**Comment by jpkorva** [comment]
Thanks for the report! I looked at the script and found two issues, which should be fixed by commit 599c9c6653. Please rebase and retry.
